---
- name: Install SonarQube on Ubuntu
  hosts: sonarqube
  become: true

  vars:
    sonarqube_version: "10.1.0.73491"
    sonarqube_user: sonar
    sonarqube_group: sonar
    install_dir: /opt/sonarqube

  tasks:
    - name: Install dependencies
      apt:
        name:
          - openjdk-17-jdk
          - unzip
          - wget
        update_cache: yes

    - name: Create sonar user
      user:
        name: "{{ sonarqube_user }}"
        system: yes
        shell: /bin/bash
        create_home: yes

    - name: Download SonarQube
      get_url:
        url: "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-{{ sonarqube_version }}.zip"
        dest: "/tmp/sonarqube.zip"

    - name: Extract SonarQube
      unarchive:
        src: /tmp/sonarqube.zip
        dest: /opt/
        remote_src: yes

    - name: Rename folder
      command: mv /opt/sonarqube-{{ sonarqube_version }} {{ install_dir }}
      args:
        creates: "{{ install_dir }}"

    - name: Change ownership
      file:
        path: "{{ install_dir }}"
        owner: "{{ sonarqube_user }}"
        group: "{{ sonarqube_group }}"
        recurse: yes

    - name: Setup systemd service
      copy:
        dest: /etc/systemd/system/sonarqube.service
        content: |
          [Unit]
          Description=SonarQube service
          After=network.target

          [Service]
          Type=forking
          ExecStart={{ install_dir }}/bin/linux-x86-64/sonar.sh start
          ExecStop={{ install_dir }}/bin/linux-x86-64/sonar.sh stop
          User={{ sonarqube_user }}
          Group={{ sonarqube_group }}
          Restart=always
          LimitNOFILE=65536

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd and enable SonarQube
      systemd:
        daemon_reload: yes
        name: sonarqube
        enabled: yes
        state: started
