---
- name: Install Docker, Git, and Maven on Ubuntu
  hosts: test
  become: true
  tasks:
    - name: Install required packages
      apt:
        name:
          - docker.io
          - git
          - maven
        state: present
        update_cache: yes

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started


