---
- name: Install Docker, Git, and Maven on Ubuntu
  hosts: test
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install Maven
      apt:
        name: maven
        state: present
